services:
  # Servicio de Prometheus y sus configs
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus ##Nombre del contenedor
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring ##red dockerizada en la cual prometheus y grafana van a estar comunicándose

  # Servicio de Grafana y sus configs
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana ##Nombre del contenedor
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin #usuario para iniciar en la webgui
      - GF_SECURITY_ADMIN_PASSWORD=admin123  # password
    networks:
      - monitoring
    depends_on:
      - prometheus
  # Node Exporter -
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - monitoring      
# Volúmenes para persistencia de datos
volumes:
  prometheus_data:
  grafana_data:

# Red dedicada para aislamiento
networks:
  monitoring:
    driver: bridge
