global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node-exporter'  # Nuevo job para métricas del host
    static_configs:
      - targets: ['node-exporter:9100']  # Nombre del servicio en Docker      